name: Pipeline - CI process with GitHub Actions

on:
  push:
    branches: [ develop, master ]

jobs:
  unit:
    name: Unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Run unit-test
        run: mvn test

  sonar:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: SonarCloud Scan
        run: mvn -B clean verify -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: List before build
      run: ls -la
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: List after build (target directory)
      run: ls -la target

